# Generated by Django 4.0.1 on 2022-02-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('POL', 'Politics'), ('SPR', 'Sports'), ('TCH', 'Technology'), ('LFS', 'Lifestyle'), ('BUS', 'Business'), ('ENT', 'Entertainment'), ('UNK', 'Unknown')], max_length=3, unique=True),
        ),
    ]
