# Generated by Django 4.0.1 on 2022-02-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='lksjd'),
            preserve_default=False,
        ),
    ]
