# Generated by Django 4.0.1 on 2022-02-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_post_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_post',
            field=models.DateField(auto_now_add=True, default='2022-02-06'),
            preserve_default=False,
        ),
    ]
