# Generated by Django 4.0.1 on 2022-02-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_post_date_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
